### ISSUE TITLE
Cannot find GB/UK postcodes

### ISSUE THREAD

**Issue by olimorris** [antonioribeiro/zipcode#3]
After changing the countryside to 'GB' I just get the returned JSON of 'Success: false'. This occurs when I change the vendor config files and when I also do:

$zipcode->setCountry('GB');

After method injecting it into my controller.

Searching for the same zipcode on Geonames, I see that it does in fact exist, but the class is not finding it.

**Comment by antonioribeiro** [comment]
Here it was falling back to zipopotamus...

Anyway, you must configure your username to use Geonames. Using 'demo' it will allow you to make one or two searches, at most.

Take a look at the docs again, have just made some changes to the source and docs and now you can configure it also via config.php, but you were already able to do this before:

```
ZipCode::setCountry('GB');

ZipCode::setQueryParameter('geonames_username', 'yourusername');

ZipCode::find('L23YL');
```
